development: &default
  adapter: postgresql
  host: localhost
  username: root
  password:
  min_messages: WARNING
  database: taskar_development

test: &test
  <<: *default
  database: taskar_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: taskar_development

cucumber:
  <<: *test